### ISSUE TITLE
Notes from GeoPython conference

### ISSUE THREAD

**Issue by kallewesterling** [Seshat-Global-History-Databank/seshat#10]
https://hackmd.io/KbMnMiuWSo2kahMfM-mZNg

**Comment by kallewesterling** [comment]
@edwardchalstrey1 I don't have access to the linked HackMD -- would you be able to open it up for me?

**Comment by edwardchalstrey1** [comment]
The most important things in this hackmd I've added as issues already, but there are a few nice links to resources still to check out
