### ISSUE TITLE
👤 [User Story]: Mobile friendly version of Seshat website

### ISSUE THREAD

**Issue by edwardchalstrey1** [Seshat-Global-History-Databank/seshat#11]
### Role

As a Seshat user,

### Desired Feature

I want to have an optimized mobile experience,

### Benefit

So that I can easily interact with the map features on my mobile device.

### Acceptance Criteria

**GIVEN** a user is accessing the map on a mobile device
**WHEN** they double tap to view a subregion
**THEN** the subregion should zoom in smoothly and accurately without lag or misinterpretation of the double tap gesture.

**GIVEN** a user is interacting with the map on a mobile device
**WHEN** they attempt to pan or zoom the map
**THEN** the map should respond quickly and intuitively to touch gestures, providing a seamless navigation experience.

**GIVEN** a user is viewing the map on a mobile device
**WHEN** the sidebar is displayed
**THEN** the sidebar should be appropriately sized and adjustable, ensuring it does not obstruct the map view or hinder interaction.

### Dependencies

- Ensure **compatibility with mobile browsers (like Gecko)**.
- Implement **responsive design principles** for mobile optimization.

### Technical Notes

- Implement and test double tap, pan, and zoom gestures specifically for mobile devices.
- Optimise loading times and performance for mobile devices.
- Adjust UI elements like the sidebar to be mobile-friendly.

### Definition of Done

- [ ] The feature fulfills all acceptance criteria.
- [ ] The code is reviewed and meets team coding standards.
- [ ] All unit, integration, and end-to-end tests are passed.
- [ ] The feature meets accessibility standards set for the project.
- [ ] The code passes the CI/CD pipeline quality controls (style and linting).
- [ ] The feature is merged into the main branch.
- [ ] The feature is deployed and functional in the QA environment.
- [ ] The feature was demonstrated to the team and accepted by the product owner.

### Comment

This is based on a recent talk that Ed gave demo-ing the current dev site:
> It worked great for me on desktop (Firefox), but it could be better optimised for mobile. Double tap to view a subregion, map pan and zoom, and the sidebar size were all problematic for me on mobile (using mobile Gecko).

**Comment by kallewesterling** [comment]
@edwardchalstrey1 I updated this user story with some details -- make sure it reflects the original issue!

**Comment by edwardchalstrey1** [comment]
TODO:

- [x] World map with just Cesium and a basic year entry
- [x] Have a way to choose minus numbers (BCE)
- [x] Don't include maps on polity pages when browsing on mobile
