### ISSUE TITLE
Merge 2 GitHub orgs?

### ISSUE THREAD

**Issue by edwardchalstrey1** [Seshat-Global-History-Databank/seshat#134]
There are now 2 organisations on GitHub:
- https://github.com/seshatdb
- https://github.com/Seshat-Global-History-Databank

Is there some way these could be merged

**Comment by kallewesterling** [comment]
Looks like it might be a bit tricky: https://github.com/orgs/community/discussions/49978

**Comment by edwardchalstrey1** [comment]
Closing this as I don't think it's very important, plus have noted the existence of the 2 orgs in the documentation
