### ISSUE TITLE
📚 [Documentation] - Add External Experts to the list of Users

### ISSUE THREAD

**Issue by MajidBenam** [Seshat-Global-History-Databank/seshat#148]
### Section of Documentation

index

### Description of Improvement

the followings should be added to the list of users in index page.

4. External Seshat Expert: User: An external collaborator who has the necessary expertise to review and make private comments on Seshat records.
5. Public User: An academic or other interested party who has created an account on the Seshat website to suggest data edits.

### Definition of Done

- [x] The documentation improvement has been developed on a branch.
- [x] A pull request has been created for the new branch to be merged into the dev branch.

**Comment by enricioni** [comment]
it does!
