### ISSUE TITLE
✨ [Feature request] - <Change date display on polity pages>

### ISSUE THREAD

**Issue by jennyreddish** [Seshat-Global-History-Databank/seshat#189]
### Description of Improvement

Hello! Question mostly for Majid: on the new view for polity pages, the date displayed at the top seems to be a (random?) date within the polity's duration. See attached screenshot of the Early Merovingian polity page -- the 543 CE date refers to the position of the slider on the map, not the polity's overall duration. I think this is a bit confusing. Can we display the overall polity duration here instead?
![Merovingian polity page](https://github.com/user-attachments/assets/10c87a9e-8a08-43c2-a2c0-632d3c903c97)

### Definition of Done

- [x] The feature has been developed on a feature branch.
- [x] The feature branch has been tested in the Staging website.
- [x] A pull request has been created for the feature branch to be merged into the dev branch.

**Comment by jennyreddish** [comment]
@MajidBenam

**Comment by MajidBenam** [comment]
Hi Jenny. Thanks for the feedback. It has been resolved both on the codebase here and on the live website.

**Comment by MajidBenam** [comment]
Done.
