### ISSUE TITLE
🐛 [BUG] - Year does not update on polity pages when moving slider

### ISSUE THREAD

**Issue by edwardchalstrey1** [Seshat-Global-History-Databank/seshat#198]
### Description

See #190 

### Reproduction steps

Navigate to a polity page map and adjust the year with slider

### Screenshots

Before and after bug introduced screenshots:

<img width="1332" alt="Screenshot 2024-12-05 at 10 26 18" src="https://github.com/user-attachments/assets/d406b05c-648f-4676-82b0-964c6e53ba5c">
<img width="1327" alt="Screenshot 2024-12-05 at 10 26 09" src="https://github.com/user-attachments/assets/d3f286f6-d5aa-4bfb-94ea-d5fdb5f9ff07">

### Definition of Done

- [ ] A fix for the bug has been developed on a branch.
- [ ] The bug fix branch has been tested in the Staging website.
- [ ] A pull request has been created for the new branch to be merged into the dev branch.

**Comment by Zsajk** [comment]
To add to this, hit enter to set year does not seem to change the year: 
![image](https://github.com/user-attachments/assets/b4c64a95-1a13-4512-ba40-ac0f011bbf58)

**Comment by edwardchalstrey1** [comment]
Thanks @Zsajk I have added a fix in #201 - let me know your thoughts
