### ISSUE TITLE
Create issue templates

### ISSUE THREAD

**Issue by edwardchalstrey1** [Seshat-Global-History-Databank/seshat#2]
It would be great if there were templates for anyone wanting new features added or bugs fixed to use when requesting development time.

During the Seshat project get together in October/November 2024 it might be a good time to train Pieter, Peter, Jim and others how to fill these out for development by Ed or Majid, especially if Majid is using issues and project board on GH.

**Comment by kallewesterling** [comment]
We have a really nice template for user stories on the Trustworthy Assurance Platform project: https://github.com/alan-turing-institute/AssurancePlatform/tree/main/.github/ISSUE_TEMPLATE

You can see an example of it in action here: https://github.com/alan-turing-institute/AssurancePlatform/issues/new?assignees=&labels=user-story&projects=&template=user-story.yaml&title=%5BUser+Story%5D:+
