### ISSUE TITLE
🐛 [BUG] - Adding a description to the 'Road' variable produces an error/lacks template

### ISSUE THREAD

**Issue by Zsajk** [Seshat-Global-History-Databank/seshat#202]
### Description

Adding a description to the 'Road' variable produces an error, also happens after coding the variable.

### Reproduction steps

```bash
1. Go to 'https://seshat-db.com/sc/roads_all/'
2. Click on 'Click to add new coded record'
3. Code variable in any way or to add any polity
4. See error
```

### Screenshots

![Screenshot 2024-12-05 155906](https://github.com/user-attachments/assets/1fe66a08-a945-445b-a61e-3e419fb01ec8)

### Definition of Done

- [x] A fix for the bug has been developed on a branch.
- [x] The bug fix branch has been tested in the Staging website.
- [x] A pull request has been created for the new branch to be merged into the dev branch.

**Comment by MajidBenam** [comment]
great catch and great explanation of the bug @Zsajk . The issue has been found and resolved on all variables on the live website and I have addressed the issue via a request to Kalle. The reason it was happening was a clash between the redirect links. Which means the data was actually created in those case, but you were directed to a page that looked like an Error. So, I hope you can find the records that you created (but you thought you didn't)! :)

**Comment by Zsajk** [comment]
> great catch and great explanation of the bug @Zsajk . The issue has been found and resolved on all variables on the live website and I have addressed the issue via a request to Kalle. The reason it was happening was a clash between the redirect links. Which means the data was actually created in those case, but you were directed to a page that looked like an Error. So, I hope you can find the records that you created (but you thought you didn't)! :)

Great , Thanks , yes I noticed that they were created so I know where they are
