### ISSUE TITLE
🐛 [BUG] - Panning doesn't always work under ESRI

### ISSUE THREAD

**Issue by jbennettgit** [Seshat-Global-History-Databank/seshat#68]
### Description

Under https://seshatdata.com/core/world_map ESRI world map you can zoom in and out but panning right and left only seems to work when you click over a polity and does not work if you click in the background map.

### Reproduction steps

1. Load the map in some year and select ESRI World Imagery
2. Try to pan the map left and right when selecting with the mouse in different regions
3. If over the background image, no panning.
4. If over a polity shape, panning works.

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

### OS

Mac

**Comment by edwardchalstrey1** [comment]
Frustratingly this seems to be the case for all the base maps (bar Cesium) on seshatdata.com but it works fine when I'm running the app on my local machine. Will have to do some investigation

**Comment by edwardchalstrey1** [comment]
This issue appears to have solved itself - I'm unsure what caused it
